on:
  push:
    branches:
      - "live"
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - webgl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2.1.1
        with:
          version: 4.4.1
          use-dotnet: false
          include-templates: false

      - name: Build game
